# name: Deploy Spring Boot Application

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up JDK 17
#         uses: actions/setup-java@v3
#         with:
#           java-version: '17'
#           distribution: 'corretto'

#       - name: Build with Maven
#         run: mvn clean install

#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-east-1

#       - name: Upload artifact to S3
#         run: |
#           ARTIFACT_NAME="demo-${{ github.sha }}.jar"
#           aws s3 cp target/demo-0.0.1-SNAPSHOT.jar s3://${{ secrets.S3_ARTIFACTS_BUCKET }}/${ARTIFACT_NAME}
#           echo "ARTIFACT_NAME=${ARTIFACT_NAME}" >> $GITHUB_ENV

#       - name: Trigger deployment
#         run: |
#           aws ssm send-command \
#             --document-name "AWS-RunShellScript" \
#             --targets "Key=tag:aws:autoscaling:groupName,Values=${{ secrets.ASG_NAME }}" \
#             --parameters 'commands=["/opt/deploy.sh ${{ secrets.S3_ARTIFACTS_BUCKET }} ${{ env.ARTIFACT_NAME }}"]'

name: Deploy Spring Boot Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload artifact to S3
        run: |
          ARTIFACT_NAME="demo-${{ github.sha }}.jar"
          aws s3 cp target/demo-0.0.1-SNAPSHOT.jar s3://${{ secrets.S3_ARTIFACTS_BUCKET }}/${ARTIFACT_NAME}
          echo "ARTIFACT_NAME=${ARTIFACT_NAME}" >> $GITHUB_ENV

      - name: Trigger deployment on EC2 via SSM
        run: |
          aws ssm send-command \
            --targets "Key=tag:aws:autoscaling:groupName,Values=${{ secrets.ASG_NAME }}" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy Spring Boot App" \
            --parameters 'commands=["bash -c \"/opt/deploy.sh '${{ secrets.S3_ARTIFACTS_BUCKET }}' '${{ env.ARTIFACT_NAME }}'\""]'
